### ISSUE TITLE
Unable to Install Dependencies on MacOS

### ISSUE THREAD

**Issue by Awesomefied** [MagnumVD/RotoForge-AI#12]
On MacOS if you try to install dependencies you get this error:
![Screenshot 2024-06-24 at 11 38 36 AM](https://github.com/MagnumVD/RotoForge-AI/assets/109247425/0b0e4db3-104f-4e60-97ee-fc8877aced05)

This is because on line 48 in the install_dependencies.py file it references python.exe:
```
python_exe = os.path.join(sys.prefix, 'bin', 'python.exe')
```
To fix this on MacOS the code needs to be changed to this:
```
python_exe = os.path.join(sys.prefix, 'bin', 'python3.10')
```

**Comment by MagnumVD** [comment]
Oh, does the deps install actually work after that change?

**Comment by MagnumVD** [comment]
Context: Change was validated on dc, magically works now (hopefully)?

Added the change in, thanks!
