### ISSUE TITLE
huggingface download wrong url + deprecated message

### ISSUE THREAD

**Issue by evilkoolade** [MagnumVD/RotoForge-AI#14]
i tried every version i have it doesn't work at all i tried putting dependencies in a dif folder and running blender as admin but still nothing

**Comment by evilkoolade** [comment]
is there any way to manually download the dependencies?

**Comment by MagnumVD** [comment]
The dependencies are downloaded when it says that in the addon preferences.
To get to the panel you need to open an image editor, switch the mode to the masking mode and select a mask. Then you should see the panel in the N-panel

**Comment by MagnumVD** [comment]
Some people look for the panel in the wrong masking tab, make sure that you're in the image editor, not the movie clip editor

**Comment by evilkoolade** [comment]
well that's great to know i couldn't find that info anywhere but i still don't have a panel there and the dependencies claim to be 8 gigs but when downloaded they only seem to be 3.39 gigs and the log has a lot of this 

RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
downloading  sam_hq_vit_tiny.pth:  ( 42.5 MB )
C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\file_download.py:1212: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(
DEBUG:filelock:Attempting to acquire lock 1388341440 on H:\New Folder\sam_hq_weights\.cache\huggingface\download\sam_hq_vit_tiny.pth:.lock
DEBUG:filelock:Lock 1388341440 acquired on H:\New Folder\sam_hq_weights\.cache\huggingface\download\sam_hq_vit_tiny.pth:.lock
DEBUG:filelock:Attempting to release lock 1388341440 on H:\New Folder\sam_hq_weights\.cache\huggingface\download\sam_hq_vit_tiny.pth:.lock
DEBUG:filelock:Lock 1388341440 released on H:\New Folder\sam_hq_weights\.cache\huggingface\download\sam_hq_vit_tiny.pth:.lock
DEBUG:urllib3.connectionpool:Resetting dropped connection: huggingface.co
DEBUG:urllib3.connectionpool:https://huggingface.co:443 "HEAD /lkeab/hq-sam/resolve/main/sam_hq_vit_tiny.pth%3A HTTP/1.1" 404 0
Traceback (most recent call last):
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/lkeab/hq-sam/resolve/main/sam_hq_vit_tiny.pth%3A

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\evilk\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\RotoForge-AI\__init__.py", line 30, in execute
    install_dependencies.download_models()
  File "C:\Users\evilk\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\RotoForge-AI\functions\install_dependencies.py", line 82, in download_models
    path = hf.hf_hub_download(repo_id="lkeab/hq-sam", filename=file, local_dir=sam_weights_dir, local_dir_use_symlinks=False)
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\utils\_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\file_download.py", line 1220, in hf_hub_download
    return _hf_hub_download_to_local_dir(
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\file_download.py", line 1448, in _hf_hub_download_to_local_dir
    (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\file_download.py", line 1752, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\file_download.py", line 1674, in get_hf_file_metadata
    r = _request_wrapper(
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\file_download.py", line 376, in _request_wrapper
    response = _request_wrapper(
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\file_download.py", line 400, in _request_wrapper
    hf_raise_for_status(response)
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\utils\_errors.py", line 315, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-66e83ff6-2e16af9260a78e1a6e435644;5b81e01d-4dc8-4ec7-a2b7-a25a5b203b62)

Entry Not Found for url: https://huggingface.co/lkeab/hq-sam/resolve/main/sam_hq_vit_tiny.pth%3A.
Error: Python: Traceback (most recent call last):
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\requests\models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/lkeab/hq-sam/resolve/main/sam_hq_vit_tiny.pth%3A

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\file_download.py", line 1752, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\file_download.py", line 1674, in get_hf_file_metadata
    r = _request_wrapper(
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\file_download.py", line 376, in _request_wrapper
    response = _request_wrapper(
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\file_download.py", line 400, in _request_wrapper
    hf_raise_for_status(response)
  File "C:\Users\evilk\MVD-addons dependencies\RotoForge AI\py_packages\huggingface_hub\utils\_errors.py", line 315, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-66e83ff6-2e16af9260a78e1a6e435644;5b81e01d-4dc8-4ec7-a2b7-a25a5b203b62)

Entry Not Found for url: https://huggingface.co/lkeab/hq-sam/resolve/main/sam_hq_vit_tiny.pth%3A.

RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.
RotoForge AI: Some dependencies are not installed, please install them using the button in the Preferences.

**Comment by MagnumVD** [comment]
Oh, yeah, I think I found the issue, thanks for reporting that.
For now, please just download the 1.0.0 version and do the install with that one. After that you can switch to the newest hotfix again.

**Comment by MagnumVD** [comment]
fixed by `a2a65a0c3d18fbe8ccbbc4f0d7a8b88a31e7c421`
