### ISSUE TITLE
Use requirements.txt to download python packages

### ISSUE THREAD

**Issue by MagnumVD** [MagnumVD/RotoForge-AI#2]
Using a requirements.txt to download the python packages needed should be better since it allows for more fine control and is faster since it'd remove the redundancy of pytorch. Currently it's downloaded once with timm and then has to be installed a second time to work with cuda. By just defining everything manually that could be skipped.

**Comment by 3pointedit** [comment]
Would this mean that I could manually download the folders for Mac?

**Comment by MagnumVD** [comment]
> Would this mean that I could manually download the folders for Mac?

Theoretically you can manually download the folders on all systems.
Because you can manually set the dependency directory in blender, you could in theory even download the dependencies onto a USB drive and just set the deps dir after you plug it in on another machine. As long as the files are there, it should work.

**Comment by 3pointedit** [comment]
Is there a download path revealed somewhere to do this, will the addon only perform the download automatically ?

**Comment by MagnumVD** [comment]
What do you mean by only perform the download automatically?

You can get the models from here:
https://huggingface.co/lkeab/hq-sam/tree/main

The downloaded pypi packages are:
timm, segment-anything-hq
And for pytorch you'll need:
torch==2.2.2, torchvision==0.17.2
