### ISSUE TITLE
I can´t generate a mask

### ISSUE THREAD

**Issue by MikeGunan** [MagnumVD/RotoForge-AI#4]
I´m trying to generate a mask, but when I click the button and wait, I get this error
![image](https://github.com/MagnumVD/RotoForge-AI/assets/170271830/827426bb-5e36-4323-8bd4-cacfb48cead3)
I´m using Blender 4.0.2 in Windows 10, 64 bits.
Pc specs:
-AMD Ryzen 5 2400G
-16 GB RAM
-NVIDIA Geforce 1050 Ti
[ROTOSCOPIAI.zip](https://github.com/MagnumVD/RotoForge-AI/files/15370726/ROTOSCOPIAI.zip)
I tried multiple times to open a new file, but I always get the same error. I don´t know what I´m doing wrong...

**Comment by MagnumVD** [comment]
Ok, I think this is a problem with the blender version. I'll update the README to account for the problem. It seems to only be the case in 4.0, so working in blender version 4.1 or 3.6 should fix your problem.

**Comment by MagnumVD** [comment]
Please tell me in the case this helped you so I can close the issue.

**Comment by MikeGunan** [comment]
Yes, now it seems to work. Thanks!
