### ISSUE TITLE
Could not get package to download on mac OS

### ISSUE THREAD

**Issue by 3pointedit** [MagnumVD/RotoForge-AI#5]
M1 macbook pro b4.2 alpha running from command line. click on install and I get this python error, no download in the background 
<img width="776" alt="Screenshot 2024-05-20 at 8 06 04 am" src="https://github.com/MagnumVD/RotoForge-AI/assets/25983373/06489452-68fe-454f-a9c0-97107d9b1013">

**Comment by MagnumVD** [comment]
Well that's dumb. I don't have a mac to work with on my end...

**Comment by MagnumVD** [comment]
I'm gonna need to find out where they have the python executable stored on the mac OS installation of blender.

**Comment by 3pointedit** [comment]
I won't be able to test again until after work tonight :( Sorry
