### ISSUE TITLE
Rotoforge tab does not appear in Blender 4.1.1

### ISSUE THREAD

**Issue by gawinaa** [MagnumVD/RotoForge-AI#6]
Installed the app to Blender 4.1.1, downloaded 8GB associated files.  No Rotoforge Tab appears in masking or anywhere else in Blender.

**Comment by MagnumVD** [comment]
Okay, let's figure this out...

Could you send a screenshot of:
- RotoForge in your preferences tab
- the image editor in the masking tab with both an image and a mask loaded
- the system console (you can open it with the button shown in the image below on Windows)
![image](https://github.com/MagnumVD/RotoForge-AI/assets/91473966/006b7465-d936-4aae-b34d-f8ef8a67523e)

In addition, I would like to know which OS and PC specs you have.

**Comment by gawinaa** [comment]
Appears to be an issue with installing dependencies.  See attached

[RotoForge_SysLog.txt](https://github.com/MagnumVD/RotoForge-AI/files/15416986/RotoForge_SysLog.txt)

**Comment by MagnumVD** [comment]
It seems to be a permission issue.

Delete the folder C:\Users\zfbot\MVD-addons dependencies\ and please retry the installation while having blender run with admin rights.

Also I'd still like to know your PC specs and OS.

**Comment by gawinaa** [comment]
Deleted directory & reinstalled as instructed, & appears log shows no errors.  Issue still persists.

![rotoforge_Addon](https://github.com/MagnumVD/RotoForge-AI/assets/44629173/88d83808-a072-4082-a2d0-2252f5503065)
![rotoforge_ImageMask](https://github.com/MagnumVD/RotoForge-AI/assets/44629173/ba891bb6-9f1f-436b-bb2e-a64edae2de5a)
![rotoforge_SysInfo](https://github.com/MagnumVD/RotoForge-AI/assets/44629173/91b8ca10-5d48-45ef-bb97-2d058832be44)
[RotoForge_SysLog.txt](https://github.com/MagnumVD/RotoForge-AI/files/15424341/RotoForge_SysLog.txt)

**Comment by MagnumVD** [comment]
You're in the wrong editor
You need to go into the Image editor. There you can find it if you switch the subtype from view to mask.

**Comment by gawinaa** [comment]
Deleted directory & reinstalled as instructed.  Appears log shows no errors.  Issue still persists.

![rotoforge_Addon](https://github.com/MagnumVD/RotoForge-AI/assets/44629173/73fde519-a9b9-4239-b5ab-c6084719f053)
![rotoforge_ImageMask](https://github.com/MagnumVD/RotoForge-AI/assets/44629173/8b0123c6-174f-4037-9f4c-9efad43978c8)
![rotoforge_SysInfo](https://github.com/MagnumVD/RotoForge-AI/assets/44629173/aa365062-3696-4a63-97df-b24469668182)
[RotoForge_SysLog_Try2.txt](https://github.com/MagnumVD/RotoForge-AI/files/15424402/RotoForge_SysLog_Try2.txt)

**Comment by MagnumVD** [comment]
But there still seems to be an issue, I think it could be your graphics card. Currently only CUDA acceleration is supported which you can find in Nvidia gpus.
But there is an experimental project called [Zluda](https://github.com/vosen/ZLUDA) which supposedly adds CUDA support to AMD gpus. Maybe that can help you out (would be very nice if you tested that actually, if it works you'd be the pioneer to a bunch of people with AMD cards)

**Comment by MagnumVD** [comment]
It has been reported to work with blender itself, hopefully it works in the same way with RotoForge

**Comment by gawinaa** [comment]
Installed it on different PC with NVIDIA GPU & it works.  So AMD GPU seem to be the problem.

Many thanks.
