### ISSUE TITLE
Masks saved in program dir if .blend is not saved

### ISSUE THREAD

**Issue by DoUhonestlyCare** [MagnumVD/RotoForge-AI#7]
Python: Traceback (most recent call last):
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs
PermissionError: [WinError 5] Access is denied: 'RotoForge masksequences'

I have to run blender as an administrator to not get this error

**Comment by DoUhonestlyCare** [comment]
forgot to mention this happens when I click track the mask

**Comment by MagnumVD** [comment]
You have to save your blend file before trying to track the mask. It will always try to save the masks in a folder next to the blend file. If the file hasn't been saved, that results in it trying to save it in the program folder.

**Comment by MagnumVD** [comment]
I'll label this as a bug with priority though, in the next release they'll get saved in the tmp folder and copied over once you save the file.
